// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9X8XL4sR1tqxX-GLu9p_IKsM5icMpONo',
    appId: '1:285913407097:android:bfa526e6b6695336f63ea8',
    messagingSenderId: '285913407097',
    projectId: 'univercity-b6b05',
    storageBucket: 'univercity-b6b05.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGDZqy4Xix8qCAksP2miAyAMYrniSWL7o',
    appId: '1:285913407097:ios:3a16eae832c6bab2f63ea8',
    messagingSenderId: '285913407097',
    projectId: 'univercity-b6b05',
    storageBucket: 'univercity-b6b05.appspot.com',
    iosBundleId: 'com.example.unipp',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_RAftgQEWJFiW4cY1SEVEo3Hk7WIyjYk',
    appId: '1:285913407097:web:c8ef035d45d82d9cf63ea8',
    messagingSenderId: '285913407097',
    projectId: 'univercity-b6b05',
    authDomain: 'univercity-b6b05.firebaseapp.com',
    storageBucket: 'univercity-b6b05.appspot.com',
    measurementId: 'G-HYF7S10354',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAGDZqy4Xix8qCAksP2miAyAMYrniSWL7o',
    appId: '1:285913407097:ios:3a16eae832c6bab2f63ea8',
    messagingSenderId: '285913407097',
    projectId: 'univercity-b6b05',
    storageBucket: 'univercity-b6b05.appspot.com',
    iosBundleId: 'com.example.unipp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD_RAftgQEWJFiW4cY1SEVEo3Hk7WIyjYk',
    appId: '1:285913407097:web:fefb4ebeefd7ba68f63ea8',
    messagingSenderId: '285913407097',
    projectId: 'univercity-b6b05',
    authDomain: 'univercity-b6b05.firebaseapp.com',
    storageBucket: 'univercity-b6b05.appspot.com',
    measurementId: 'G-ZJZSP2KYDB',
  );
}
